// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnvxbkukplapkxobzhct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJudnhia3VrcGxhcGt4b2J6aGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDA3NzQsImV4cCI6MjA3MDIxNjc3NH0.CeDL0ROtUENzDXHsH0WYh4oCUFugfxkCASiRTbRh0N0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});